# Generated by Django 3.1 on 2021-03-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210319_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_t_platform',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='t_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tutor_or_ps',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video_or_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
