# Generated by Django 3.1 on 2021-03-21 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210321_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_t_platform',
        ),
        migrations.RemoveField(
            model_name='post',
            name='t_location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tutor_or_ps',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_or_person',
        ),
    ]
