# Generated by Django 3.1 on 2021-03-21 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210321_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='TF_Post',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('virtual', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=200)),
                ('school_level', models.CharField(max_length=200)),
                ('topics', models.CharField(max_length=200)),
            ],
            bases=('posts.post',),
        ),
    ]
