# Generated by Django 3.1 on 2021-03-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_tf_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tf_post',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tf_post',
            name='school_level',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tf_post',
            name='state',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='tf_post',
            name='topics',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tf_post',
            name='virtual',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
