# Generated by Django 3.1 on 2021-03-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_eduprovider',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.IntegerField(choices=[(1, 'Educational Provider'), (2, 'Teacher or Tutor'), (3, 'Parent or Student')], default=1),
            preserve_default=False,
        ),
    ]
